trigger:
- main

pool: <YourSelfHostedPoolName>

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Import-Module SQLServer
      Import-Module Az.Accounts
      
      $clientid = "<ServicePrincipalAppID>";
      $tenantid = "<ServicePrincipalTenantID>";
      $secret = "<ServicePrincipalSecret>";
      
      $request = Invoke-RestMethod -Method POST -Uri "https://login.microsoftonline.com/$tenantid/oauth2/token" -Body @{ resource="https://database.windows.net/"; grant_type="client_credentials"; client_id=$clientid; client_secret=$secret } -ContentType "application/x-www-form-urlencoded";
      $access_token = $request.access_token;
      
      Invoke-Sqlcmd -ServerInstance <DatabaseServerName>.database.windows.net -Database <DatabaseName> -AccessToken $access_token -query 'select getdate() as timeofquery';

- task: AzurePowerShell@5
  inputs:
    azureSubscription: '<ServiceConnectionName>'
    ScriptType: 'InlineScript'
    Inline: |
      Import-Module SQLServer
      Import-Module Az.Accounts

      $access_token = (Get-AzAccessToken -ResourceUrl https://database.windows.net).Token

      Invoke-Sqlcmd -ServerInstance <DatabaseServerName>.database.windows.net -Database <DatabaseName> -AccessToken $access_token -query 'select getdate() as timeofquery';
      
    azurePowerShellVersion: 'LatestVersion'